### PR TITLE
Update Türkçe.lng

### PR DESCRIPTION
**Pull request by thrylmz**
Minor fix

### CODE REVIEW

**Comment by zenden2k** [comment]
But this commit is utf-8 encoded. Github does not show diff for UTF-16 files.
Just compare with your previous pull request:
https://github.com/zenden2k/image-uploader/pull/101/files
https://github.com/zenden2k/image-uploader/pull/99/files

**Comment by thrylmz** [comment]
I see, I'll be more careful. Thanks.

**Comment by thrylmz** [comment]
BTW, The program, does not read "5f1de092" and "cec2a305" values.
imu

**Comment by zenden2k** [comment]
Fixed in the latest build
http://zenden.ws/imageuploader_downloads

**Pull request merged**
